### PR TITLE
Tori housh patch 1

### PR DESCRIPTION
**Pull request by ToriHoush**
apparently creating a pull request from the branch is a request to merge with the master

### CODE REVIEW

**Review by ToriHoush — COMMENTED** [review]
don't need to bring in all the edits and there are subsequent changes to this file. let's attempt to discard the first two and only take the ultimate.

**Review by ToriHoush — COMMENTED** [review]
another revision to the first file.  let's skip this one too.

**Review by ToriHoush — COMMENTED** [review]
still trying to discover how to select just one of the versions for merge.

**Review by ToriHoush — COMMENTED** [review]
finally hovering over gray choices - and as the author i can't really approve or request a change. 
brilliant.
lets see if i can even remove unwanted iterations of edit. 
doubtful in this git world of all history for all time.
will attempt to prove myself wrong in this assumption

**Review by johnmuth81 — APPROVED** [review]
Looks good to me

**Comment by johnmuth81** [comment]
Hi Tori. I approved the pull request. I'll leave it to you to do the merge.

**Comment by ToriHoush** [comment]
Rebase and merge ... maybe this removes all the chatter and versions before the merge ...

**Pull request merged**
